### ISSUE TITLE
Request to implement switch profile using KMlink

### ISSUE THREAD

**Issue by hepabolu** [Corcules/KMlink#10]
Problem to be solved: I have an entire profile dedicated to window management (inspired by your example and using your images for it)  and I want to use it as a kind of 'folder' so that I can access it from every other profile I have. To get that working I need a 'back to previous profile' button.

There is a way to switch profile programmatically, but that is part of the API.
Is it possible to build that into the KMlink plugin?

This could be used as follows:
- KM macro 'switch to profile' gets 2 parameters: current profile name and target profile name. KM macro sets a variable with the current profile name and calls 'switch to profile' with the target profile name.
- KM macro 'switch to previous profile' switches to the profile with the name set in the variable.

PS. I know that I can put the window management profile into a folder and copy the folder to each profile, but when I want to change the behaviour of one of the buttons, I need to copy the folder to every profile again and I'm still tweaking the way the buttons should behave.

**Comment by Corcules** [comment]
Hello Hepabolu

Well, "switch to profil" is absolutly not the purpose of KMLink. So short answer is no.

If you look at my others repositories, you will find another plugin "switch to profil". May be useful as a starting point... But at the time i made it there were some limits on the streamdeck api : the only profil you can switch to from a plugin has to be part of the plugin... very annoying.

Well i believe that this limit is or is going to be opened. But i didn't test it... well i'm curious now...;-)

Other way may be to use a small dedicated app (easy with AppleScript) to switch to that profil. You will find more info on that in the Keyboard Maestro forum...

Last but not the cheaper, buy another streamdeck... on that change with the apps, one that never change.
