### ISSUE TITLE
Source Code

### ISSUE THREAD

**Issue by skwashd** [Corcules/KMlink#11]
It would be good to have access to the source code for `KMLink` and have all the code in the repo rather than just a zipped version of the plugin. Do you have any plans to release the source?

**Comment by Corcules** [comment]
No, no plan to open the source.

But if you have some idea of improvement or need a new fonctionnality in KMLink, please let me know by adding a new issue on this repo. I would be glad to add it if i can.

By the way, you will find a lot of ressources and opened code on [Elgato Developper website](https://developer.elgato.com/).
This is where i started from.
