### ISSUE TITLE
Button id always send row/column id but not the setted name

### ISSUE THREAD

**Issue by nagaitsev** [Corcules/KMlink#2]
Hello! Thank you for your plugin for stream deck! I want to use Keyboad Maestro link with different profiles, but when I set stream deck key in one profile I can't use the same key with different profile Button iD always the same regardless setted new name. Could you help with this? Is it my mistake or issue?

different profiles
https://i.profilecdn.ru/fpn6gkq6q9.jpg
https://i.profilecdn.ru/yw5j6g62j5.jpg

same link
https://i.profilecdn.ru/8odjmy8zet.png

**Comment by Corcules** [comment]
Hello, 

I guess your are not in the right place. It seems you are talking about the official Keyboard Maestro plugin for StreamDeck, made by Stairways.
But your issue should be resolve by using KMlink plugin instead, my plugin which is simpler but but more efficient with streamdeck profiles.
