### ISSUE TITLE
km macros not triggering

### ISSUE THREAD

**Issue by ac4lt** [Corcules/KMlink#5]
I came across this project today trying to find a solution to the physical keyboard/logical keyboard disconnect between stream deck and the keyboard maestro/streamdeck integration.

I installed the plugin and was easily able to add a "km link" key on the stream deck. It puled down the list of macros from keyboard maestro (and organized them beautifully!). However, when I press that key on the stream deck, the km macro never gets executed. So far as I can tell, I've configured things properly but the macro is never invoked.

Using release 1.4.1 of this plugin.
Stream deck 4.8.1
keyboard maestro 9.0.5
MacOS 10.15.5

If there are any logs that would help, let me know and I'll grab them.

**Comment by Corcules** [comment]
Hello, 
Well, macOS 10.5 is a quite old os version, i guess you should start here.
