### ISSUE TITLE
Question / feature request

### ISSUE THREAD

**Issue by JohanNiklasson** [Corcules/KMlink#7]
Hi

Many of us use two computers with the Stream Deck. One to run one streaming application and the second computer to run graphics. So in my case, MacBook Air M1 (computer 1) and a MacBook Pro (computer 2).

The Stream Deck is connected to computer 1. I would like too be able to keep it connected to computer one but trigger actions (Keyboard Maestro Macros) on computer 2.

I thought I could do it by using the "Trigger by URL" option but that does not work.

Is it possible to make the Stream Deck trigger actions/macros on computer 2?

Best Regards
Johan Niklasson

**Comment by Corcules** [comment]
Hi Johan, 

I guess yes this would be possible quite easily...
I imagine this scenario :
- SD call a KM macro on CP1
- KM macro on CP1 call a KM macro on CP2 or trigger it over network.

So i think the point is how to trigger a macro on CP2 from a macro on CP1.
You should check KM wiki or ask for it on their forum, not there...;-)
