### ISSUE TITLE
Issues with MacOS 11.3

### ISSUE THREAD

**Issue by timlawson-uk** [Corcules/KMlink#8]
The KMlink plugin has stopped working for me since I updated to MacOS 11.3. Is this a known issue?
It look like Stream Deck cannot link to the KM macros - just spins - see screenshot.

<img width="584" alt="Screenshot 2021-04-29 at 10 20 23" src="https://user-images.githubusercontent.com/69344997/116529248-a59d1380-a8d4-11eb-8ce8-15de7a2ca5ac.png">

**Comment by goerz** [comment]
I've been seeing the same problem. Today it got worse: 

The Macro and Parameter fields are now missing entirely:

![Screen Shot 2021-04-29 at 19 10 24](https://user-images.githubusercontent.com/112306/116629121-8f1baa00-a91e-11eb-93b1-df1065ee1294.png)

**Comment by timlawson-uk** [comment]
Does not look good @goerz . I am wondering if I should remove the plugin and reinstall it but I nam worried that it will delete all the buttons I have set up... loads of work to sort that mess out if so as I use this plugin a lot!

@Corcules are you able to suggest what we should do? Thanks.

**Comment by Corcules** [comment]
Hi guys, 
Sorry, i'm still in macOS 10.n on all my macs. So i don't have tested the plugin on Big Sur yet. 

@timlawson-uk, you may try to remove/reinstall the plugin. I think your buttons will still be there unchanged after that.
But i suggest to do a backup of your SD profils before. (on SD app preferences panel, "profils" tab, right-clic on the profil to export).

Anyway, it seems to have something to do with permissions and access to files. 
You may try to check and rebuilt permissions. 

I did not plan to install Big Sur before this summer, i will see to do it sooner...

**Comment by goerz** [comment]
Looks like the problem resolved itself for me (without me doing anything)

**Comment by Corcules** [comment]
@goerz  super!
@timlawson-uk please Tim, let me known...

**Comment by timlawson-uk** [comment]
@Corcules I have removed and reinstalled the plugin, re-booted the Mac and it is now working OK! 😀 The buttons did stay the same.

Many thanks for your support and such a great plugin.... I use it many times each day!
